#------------------------------------------------------------------------------
# usage: Use tutor to enable the Open edX Credentials service plugin
#------------------------------------------------------------------------------
name: Open edX Tutor k8s enable Credentials plugin
description: Github Action to install and enable the Tutor plugin - Open edX Credentials service
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  version:
    description: 'The version of the tutor plugin to install. Default: latest, which installs from the main branch.'
    required: false
    default: "latest"
    type: string
  namespace:
    description: 'The Kubernetes namesapce to which the Open edX platform environment will be deployed. Example: openedx-prod'
    required: true
    type: string
  aws-ecr-uri:
    description: 'The URI for the AWS ECR repository. Example: 621672204142.dkr.ecr.us-east-2.amazonaws.com/openedx_credentials:latest'
    required: true
    type: string
  common-logo-url:
    description: 'Example: https://www.edx.org/images/logos/edx-logo-elm.svg'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    # retrieve the MySQL connection parameters that we created in Terraform
    # and then stored in Kubernetes secrets. These include:
    #
    #   CREDENTIALS_MYSQL_PASSWORD=******
    #   CREDENTIALS_MYSQL_USERNAME=prod-credentials
    #   MYSQL_HOST=mrionline-global-live.cxtpn79fpu7n.us-east-2.rds.amazonaws.com
    #   MYSQL_PORT=3306
    - name: fetch MySQL configuration from Kubernetes secrets
      id: get-mysql-secret
      uses: openedx-actions/tutor-k8s-get-secret@v1.0.0
      with:
        eks-namespace: ${{ inputs.namespace }}
        eks-secret-name: mysql-credentials

    # IMPORTANT: you must run tutor_build_credentials first.
    - name: install credentials plugin
      id: install-plugin
      shell: bash
      run: pip install git+https://github.com/lpm0073/tutor-contrib-credentials${{ inputs.tutor-version != 'latest' && format('@{0}', inputs.tutor-version) || '' }}

    - name: Enable and configure credentials plugin
      id: save-config
      shell: bash
      run: |-
        tutor plugins enable credentials
        tutor config save --set CREDENTIALS_DOCKER_IMAGE=${{ inputs.aws-ecr-uri }} \
                          --set CREDENTIALS_LOGO_URL="${{ inputs.common-logo-url }}" \
                          --set CREDENTIALS_FAVICON_URL="${{ inputs.common-logo-url }}" \
